language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install codecov

install:
  - pip install --editable .
  - pip install --upgrade pytest mock

script:
  - cd tests
  - py.test --verbose

after_success:
  - codecov
